# Generated by Django 4.2.4 on 2023-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='penalties',
            field=models.IntegerField(default=0),
        ),
    ]
