# Generated by Django 4.2.4 on 2023-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_player_penalties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('jack', 'jack'), ('queen', 'queen'), ('king', 'king'), ('ace', 'ace')], max_length=10),
        ),
    ]
